server {
  listen 3000;
  server_name _;
  resolver 127.0.0.11 ipv6=off;
  set $ops_api http://ops-api:9080;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass $ops_api;
  }

  location /health {
    proxy_pass $ops_api;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
